### ISSUE TITLE
Create a function that will handle the input, output, and calculation

### ISSUE THREAD

**Issue by resoluteCoder** [shaypheraddison/Baseball-Stat-Line-Calculator#1]
To extend the functionality in a more readable and maintainable way. Try create three separate functions that will take the input from the user, calculate data based on input, print the calculation to the user

Example names for the functions could be:
- `get_input`
- `calc_batting_avg`
- `print_avg`

**Comment by shaypheraddison** [comment]
x , y = float(input("How many hits?: ")) , float(input("How many at-bats?: "))
calc_avg = x / y
print(f"The batting average is: = {calc_avg:.3f}")

Would this be more acceptable? I am trying to figure out how to get rid of the leading 0 with the decimal

**Comment by resoluteCoder** [comment]
The issue revolves around creating functions to separate logic and increase usability.
For example:

```python
def add_two(num):
    return num + 2
``` 

I would try to do that with each calculation, input, and display messages that you have or if there is repetition then try to generalize the function.

Let's reopen this issue 😄

**Comment by resoluteCoder** [comment]
Also let's start implementing pull requests into your flow. 

Here is a link for the previous comment about functions: https://pythonbasics.org/functions/
Here is a link about PR's: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by resoluteCoder** [comment]
You can create a new branch via the GUI tool or via cli like so `git checkout -b implement-functions`

**Comment by resoluteCoder** [comment]
Once you have add all the code and you are ready to push to github follow these steps:
- `git add .`
- `git commit -m 'refactored logic to incorporate functions`
- `git push origin implement-functions`
Or again use the github GUI
